Update _open.py
Currently if visidata is given a URI handler it doesn't understand, like `abc://` it will fail in the console like the following:
```
Traceback (most recent call last):
  File "bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/Users/geekscrapy/vd_dev/visidata_upstream/visidata/main.py", line 299, in vd_cli
    rc = main_vd()
  File "/Users/geekscrapy/vd_dev/visidata_upstream/visidata/main.py", line 213, in main_vd
    vs = vd.openSource(p, **opts)
  File "/Users/geekscrapy/vd_dev/visidata_upstream/visidata/_open.py", line 78, in openSource
    vs = vd.openPath(Path(p), filetype=filetype)  # convert to Path and recurse
  File "/Users/geekscrapy/vd_dev/visidata_upstream/visidata/_open.py", line 45, in openPath
    return vd.getGlobals()[openfunc](p, filetype=filetype)
KeyError: 'openurl_abc'
```

My suggestion is to catch this KeyError and returns the following instead:
`Error: no loader for url schema: abc`