[viewtsv] fix missing import and argument to open_tsv
Fixes:
`NameError: name 'VisiData' is not defined`
and 

```
    run(*(open_tsv(Path(fn)) for fn in sys.argv[1:]))
          ^^^^^^^^^^^^^^^^^^
TypeError: open_tsv() missing 1 required positional argument: 'p'
```